;;; Compiled snippets and support files for `css-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'css-mode
                     '(("zoo" "zoom: 1;" "zoo" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/zoo" nil nil)
                       ("z:a" "z-index: auto;" "z:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/z_a" nil nil)
                       ("z" "z-index: $0;" "z" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/z" nil nil)
                       ("wow:u" "word-wrap: unrestricted;" "wow:u" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wow_u" nil nil)
                       ("wow:s" "word-wrap: suppress;" "wow:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wow_s" nil nil)
                       ("wow:no" "word-wrap: none;" "wow:no" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wow_no" nil nil)
                       ("wow:n" "word-wrap: normal;" "wow:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wow_n" nil nil)
                       ("wow" "word-wrap: $0;" "wow" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wow" nil nil)
                       ("wos" "word-spacing: $0;" "wos" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wos" nil nil)
                       ("wob:n" "word-break: normal;" "wob:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wob_n" nil nil)
                       ("wob:l" "word-break: loose;" "wob:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wob_l" nil nil)
                       ("wob:k" "word-break: keep-all;" "wob:k" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wob_k" nil nil)
                       ("wob:bs" "word-break: break-strict;" "wob:bs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wob_bs" nil nil)
                       ("wob:ba" "word-break: break-all;" "wob:ba" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wob_ba" nil nil)
                       ("wob" "word-break: $0;" "wob" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wob" nil nil)
                       ("wid" "widows: $0;" "wid" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/wid" nil nil)
                       ("whsc:n" "white-space-collapse: normal;" "whsc:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whsc_n" nil nil)
                       ("whsc:l" "white-space-collapse: loose;" "whsc:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whsc_l" nil nil)
                       ("whsc:k" "white-space-collapse: keep-all;" "whsc:k" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whsc_k" nil nil)
                       ("whsc:bs" "white-space-collapse: break-strict;" "whsc:bs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whsc_bs" nil nil)
                       ("whsc:ba" "white-space-collapse: break-all;" "whsc:ba" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whsc_ba" nil nil)
                       ("whsc" "white-space-collapse: $0;" "whsc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whsc" nil nil)
                       ("whs:pw" "white-space: pre-wrap;" "whs:pw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whs_pw" nil nil)
                       ("whs:pl" "white-space: pre-line;" "whs:pl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whs_pl" nil nil)
                       ("whs:p" "white-space: pre;" "whs:p" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whs_p" nil nil)
                       ("whs:nw" "white-space: nowrap;" "whs:nw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whs_nw" nil nil)
                       ("whs:n" "white-space: normal;" "whs:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whs_n" nil nil)
                       ("whs" "white-space: $0;" "whs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/whs" nil nil)
                       ("w:a" "width: auto;" "w:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/w_a" nil nil)
                       ("w" "width: $0;" "w" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/w" nil nil)
                       ("va:tt" "vertical-align: text-top;" "va:tt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_tt" nil nil)
                       ("va:tb" "vertical-align: text-bottom;" "va:tb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_tb" nil nil)
                       ("va:t" "vertical-align: top;" "va:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_t" nil nil)
                       ("va:sup" "vertical-align: super;" "va:sup" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_sup" nil nil)
                       ("va:sub" "vertical-align: sub;" "va:sub" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_sub" nil nil)
                       ("va:m" "vertical-align: middle;" "va:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_m" nil nil)
                       ("va:bl" "vertical-align: baseline;" "va:bl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_bl" nil nil)
                       ("va:b" "vertical-align: bottom;" "va:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va_b" nil nil)
                       ("va" "vertical-align: $0;" "va" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/va" nil nil)
                       ("v:v" "visibility: visible;" "v:v" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/v_v" nil nil)
                       ("v:h" "visibility: hidden;" "v:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/v_h" nil nil)
                       ("v:c" "visibility: collapse;" "v:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/v_c" nil nil)
                       ("v" "visibility: $0;" "v" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/v" nil nil)
                       ("tw:u" "text-wrap: unrestricted;" "tw:u" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tw_u" nil nil)
                       ("tw:s" "text-wrap: suppress;" "tw:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tw_s" nil nil)
                       ("tw:no" "text-wrap: none;" "tw:no" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tw_no" nil nil)
                       ("tw:n" "text-wrap: normal;" "tw:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tw_n" nil nil)
                       ("tw" "text-wrap: $0;" "tw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tw" nil nil)
                       ("tt:u" "text-transform: uppercase;" "tt:u" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tt_u" nil nil)
                       ("tt:n" "text-transform: none;" "tt:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tt_n" nil nil)
                       ("tt:l" "text-transform: lowercase;" "tt:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tt_l" nil nil)
                       ("tt:c" "text-transform: capitalize;" "tt:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tt_c" nil nil)
                       ("tt" "text-transform: $0;" "tt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tt" nil nil)
                       ("tsh:n" "text-shadow: none;" "tsh:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tsh_n" nil nil)
                       ("tsh+" "text-shadow: ${1:0} ${2:0} ${3:0} #${0:000};" "tsh+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tsh+" nil nil)
                       ("tsh" "text-shadow: $0;" "tsh" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tsh" nil nil)
                       ("tr:n" "text-replace: none;" "tr:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tr_n" nil nil)
                       ("tr" "text-replace: $0;" "tr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tr" nil nil)
                       ("to:n" "text-outline: none;" "to:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/to_n" nil nil)
                       ("to+" "text-outline: ${1:0} ${2:0} #${0:000};" "to+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/to+" nil nil)
                       ("to" "text-outline: $0;" "to" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/to" nil nil)
                       ("tj:t" "text-justify: tibetan;" "tj:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_t" nil nil)
                       ("tj:k" "text-justify: kashida;" "tj:k" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_k" nil nil)
                       ("tj:iw" "text-justify: inter-word;" "tj:iw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_iw" nil nil)
                       ("tj:ii" "text-justify: inter-ideograph;" "tj:ii" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_ii" nil nil)
                       ("tj:ic" "text-justify: inter-cluster;" "tj:ic" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_ic" nil nil)
                       ("tj:d" "text-justify: distribute;" "tj:d" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_d" nil nil)
                       ("tj:a" "text-justify: auto;" "tj:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj_a" nil nil)
                       ("tj" "text-justify: $0;" "tj" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tj" nil nil)
                       ("ti:-" "text-indent: -9999px;" "ti:-" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ti_-" nil nil)
                       ("ti" "text-indent: $0;" "ti" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ti" nil nil)
                       ("th:t" "text-height: text-size;" "th:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/th_t" nil nil)
                       ("th:m" "text-height: max-size;" "th:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/th_m" nil nil)
                       ("th:f" "text-height: font-size;" "th:f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/th_f" nil nil)
                       ("th:a" "text-height: auto;" "th:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/th_a" nil nil)
                       ("th" "text-height: $0;" "th" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/th" nil nil)
                       ("te:n" "text-emphasis: none;" "te:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_n" nil nil)
                       ("te:dt" "text-emphasis: dot;" "te:dt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_dt" nil nil)
                       ("te:ds" "text-emphasis: disc;" "te:ds" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_ds" nil nil)
                       ("te:c" "text-emphasis: circle;" "te:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_c" nil nil)
                       ("te:b" "text-emphasis: before;" "te:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_b" nil nil)
                       ("te:ac" "text-emphasis: accent;" "te:ac" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_ac" nil nil)
                       ("te:a" "text-emphasis: after;" "te:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te_a" nil nil)
                       ("te" "text-emphasis: $0;" "te" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/te" nil nil)
                       ("td:u" "text-decoration: underline;" "td:u" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/td_u" nil nil)
                       ("td:o" "text-decoration: overline;" "td:o" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/td_o" nil nil)
                       ("td:n" "text-decoration: none;" "td:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/td_n" nil nil)
                       ("td:l" "text-decoration: line-through;" "td:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/td_l" nil nil)
                       ("td" "text-decoration: $0;" "td" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/td" nil nil)
                       ("tbl:f" "table-layout: fixed;" "tbl:f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tbl_f" nil nil)
                       ("tbl:a" "table-layout: auto;" "tbl:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tbl_a" nil nil)
                       ("tbl" "table-layout: $0;" "tbl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tbl" nil nil)
                       ("tal:r" "text-align-last: right;" "tal:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tal_r" nil nil)
                       ("tal:l" "text-align-last: left;" "tal:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tal_l" nil nil)
                       ("tal:c" "text-align-last: center;" "tal:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tal_c" nil nil)
                       ("tal:a" "text-align-last: auto;" "tal:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tal_a" nil nil)
                       ("tal" "text-align-last: $0;" "tal" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/tal" nil nil)
                       ("ta:r" "text-align: right;" "ta:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ta_r" nil nil)
                       ("ta:l" "text-align: left;" "ta:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ta_l" nil nil)
                       ("ta:c" "text-align: center;" "ta:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ta_c" nil nil)
                       ("ta" "text-align: $0;" "ta" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ta" nil nil)
                       ("t:a" "top: auto;" "t:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/t_a" nil nil)
                       ("t" "top: $0;" "t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/t" nil nil)
                       ("rz:v" "resize: vertical;" "rz:v" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/rz_v" nil nil)
                       ("rz:n" "resize: none;" "rz:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/rz_n" nil nil)
                       ("rz:h" "resize: horizontal;" "rz:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/rz_h" nil nil)
                       ("rz:b" "resize: both;" "rz:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/rz_b" nil nil)
                       ("rz" "resize: $0;" "rz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/rz" nil nil)
                       ("r:a" "right: auto;" "r:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/r_a" nil nil)
                       ("r" "right: $0;" "r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/r" nil nil)
                       ("q:ru" "quotes: '\\00AB' '\\00BB' '\\201E' '\\201C';" "q:ru" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/q_ru" nil nil)
                       ("q:n" "quotes: none;" "q:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/q_n" nil nil)
                       ("q:en" "quotes: '\\201C' '\\201D' '\\2018' '\\2019';" "q:en" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/q_en" nil nil)
                       ("q" "quotes: $0;" "q" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/q" nil nil)
                       ("pt" "padding-top: $0;" "pt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pt" nil nil)
                       ("pr" "padding-right: $0;" "pr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pr" nil nil)
                       ("pos:s" "position: static;" "pos:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pos_s" nil nil)
                       ("pos:r" "position: relative;" "pos:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pos_r" nil nil)
                       ("pos:f" "position: fixed;" "pos:f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pos_f" nil nil)
                       ("pos:a" "position: absolute;" "pos:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pos_a" nil nil)
                       ("pos" "position: $0;" "pos" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pos" nil nil)
                       ("pl" "padding-left: $0;" "pl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pl" nil nil)
                       ("pgbi:av" "page-break-inside: avoid;" "pgbi:av" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbi_av" nil nil)
                       ("pgbi:a" "page-break-inside: auto;" "pgbi:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbi_a" nil nil)
                       ("pgbi" "page-break-inside: $0;" "pgbi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbi" nil nil)
                       ("pgbb:r" "page-break-before: right;" "pgbb:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbb_r" nil nil)
                       ("pgbb:l" "page-break-before: left;" "pgbb:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbb_l" nil nil)
                       ("pgbb:aw" "page-break-before: always;" "pgbb:aw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbb_aw" nil nil)
                       ("pgbb:a" "page-break-before: auto;" "pgbb:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbb_a" nil nil)
                       ("pgbb" "page-break-before: $0;" "pgbb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgbb" nil nil)
                       ("pgba:r" "page-break-after: right;" "pgba:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgba_r" nil nil)
                       ("pgba:l" "page-break-after: left;" "pgba:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgba_l" nil nil)
                       ("pgba:aw" "page-break-after: always;" "pgba:aw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgba_aw" nil nil)
                       ("pgba:a" "page-break-after: auto;" "pgba:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgba_a" nil nil)
                       ("pgba" "page-break-after: $0;" "pgba" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pgba" nil nil)
                       ("pb" "padding-bottom: $0;" "pb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/pb" nil nil)
                       ("p:4" "padding: ${1:0} ${2:0} ${3:0} ${0:0};" "p:4" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/p_4" nil nil)
                       ("p:3" "padding: ${1:0} ${2:0} ${0:0};" "p:3" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/p_3" nil nil)
                       ("p:2" "padding: ${1:0} ${0:0};" "p:2" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/p_2" nil nil)
                       ("p:0" "padding: 0;" "p:0" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/p_0" nil nil)
                       ("p" "padding: $0;" "p" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/p" nil nil)
                       ("ow" "outline-width: $0;" "ow" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ow" nil nil)
                       ("ovy:v" "overflow-y: visible;" "ovy:v" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovy_v" nil nil)
                       ("ovy:s" "overflow-y: scroll;" "ovy:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovy_s" nil nil)
                       ("ovy:h" "overflow-y: hidden;" "ovy:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovy_h" nil nil)
                       ("ovy:a" "overflow-y: auto;" "ovy:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovy_a" nil nil)
                       ("ovy" "overflow-y: $0;" "ovy" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovy" nil nil)
                       ("ovx:v" "overflow-x: visible;" "ovx:v" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovx_v" nil nil)
                       ("ovx:s" "overflow-x: scroll;" "ovx:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovx_s" nil nil)
                       ("ovx:h" "overflow-x: hidden;" "ovx:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovx_h" nil nil)
                       ("ovx:a" "overflow-x: auto;" "ovx:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovx_a" nil nil)
                       ("ovx" "overflow-x: $0;" "ovx" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovx" nil nil)
                       ("ovs:s" "overflow-style: scrollbar;" "ovs:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovs_s" nil nil)
                       ("ovs:p" "overflow-style: panner;" "ovs:p" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovs_p" nil nil)
                       ("ovs:mv" "overflow-style: move;" "ovs:mv" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovs_mv" nil nil)
                       ("ovs:mq" "overflow-style: marquee;" "ovs:mq" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovs_mq" nil nil)
                       ("ovs:a" "overflow-style: auto;" "ovs:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovs_a" nil nil)
                       ("ovs" "overflow-style: $0;" "ovs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ovs" nil nil)
                       ("ov:v" "overflow: visible;" "ov:v" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ov_v" nil nil)
                       ("ov:s" "overflow: scroll;" "ov:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ov_s" nil nil)
                       ("ov:h" "overflow: hidden;" "ov:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ov_h" nil nil)
                       ("ov:a" "overflow: auto;" "ov:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ov_a" nil nil)
                       ("ov" "overflow: $0;" "ov" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ov" nil nil)
                       ("os" "outline-style: $0;" "os" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/os" nil nil)
                       ("orp" "orphans: $0;" "orp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/orp" nil nil)
                       ("op:ms" "-ms-filter: 'progid:DXImageTransform.Microsoft.Alpha(Opacity=${0:100})';" "op:ms" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/op_ms" nil nil)
                       ("op:ie" "filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=${0:100});" "op:ie" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/op_ie" nil nil)
                       ("op" "opacity: $0;" "op" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/op" nil nil)
                       ("oo" "outline-offset: $0;" "oo" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/oo" nil nil)
                       ("oc:i" "outline-color: invert;" "oc:i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/oc_i" nil nil)
                       ("oc" "outline-color: ${0:#000};" "oc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/oc" nil nil)
                       ("o:n" "outline: none;" "o:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/o_n" nil nil)
                       ("o+" "outline: ${1:1px} ${2:solid} #${0:000};" "o+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/o+" nil nil)
                       ("o" "outline: $0;" "o" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/o" nil nil)
                       ("mt:a" "margin-top: auto;" "mt:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mt_a" nil nil)
                       ("mt" "margin-top: $0;" "mt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mt" nil nil)
                       ("mr:a" "margin-right: auto;" "mr:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mr_a" nil nil)
                       ("mr" "margin-right: $0;" "mr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mr" nil nil)
                       ("ml:a" "margin-left: auto;" "ml:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ml_a" nil nil)
                       ("ml" "margin-left: $0;" "ml" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ml" nil nil)
                       ("miw" "min-width: $0;" "miw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/miw" nil nil)
                       ("mih" "min-height: $0;" "mih" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mih" nil nil)
                       ("mb:a" "margin-bottom: auto;" "mb:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mb_a" nil nil)
                       ("mb" "margin-bottom: $0;" "mb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mb" nil nil)
                       ("maw:n" "max-width: none;" "maw:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/maw_n" nil nil)
                       ("maw" "max-width: $0;" "maw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/maw" nil nil)
                       ("mah:n" "max-height: none;" "mah:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mah_n" nil nil)
                       ("mah" "max-height: $0;" "mah" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/mah" nil nil)
                       ("m:a" "margin: auto;" "m:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/m_a" nil nil)
                       ("m:4" "margin: ${1:0} ${2:0} ${3:0} ${0:0};" "m:4" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/m_4" nil nil)
                       ("m:3" "margin: ${1:0} ${2:0} ${0:0};" "m:3" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/m_3" nil nil)
                       ("m:2" "margin: ${1:0} ${0:0};" "m:2" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/m_2" nil nil)
                       ("m:0" "margin: 0;" "m:0" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/m_0" nil nil)
                       ("m" "margin: $0;" "m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/m" nil nil)
                       ("lts" "letter-spacing: $0;" "lts" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lts" nil nil)
                       ("list:ur" "list-style-type: upper-roman;" "list:ur" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_ur" nil nil)
                       ("list:s" "list-style-type: square;" "list:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_s" nil nil)
                       ("list:n" "list-style-type: none;" "list:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_n" nil nil)
                       ("list:lr" "list-style-type: lower-roman;" "list:lr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_lr" nil nil)
                       ("list:dclz" "list-style-type: decimal-leading-zero;" "list:dclz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_dclz" nil nil)
                       ("list:dc" "list-style-type: decimal;" "list:dc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_dc" nil nil)
                       ("list:d" "list-style-type: disc;" "list:d" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_d" nil nil)
                       ("list:c" "list-style-type: circle;" "list:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list_c" nil nil)
                       ("list" "list-style-type: $0;" "list" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/list" nil nil)
                       ("lisp:o" "list-style-position: outside;" "lisp:o" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lisp_o" nil nil)
                       ("lisp:i" "list-style-position: inside;" "lisp:i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lisp_i" nil nil)
                       ("lisp" "list-style-position: $0;" "lisp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lisp" nil nil)
                       ("lisi:n" "list-style-image: none;" "lisi:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lisi_n" nil nil)
                       ("lisi" "list-style-image: url($0);" "lisi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lisi" nil nil)
                       ("lis:n" "list-style: none;" "lis:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lis_n" nil nil)
                       ("lis" "list-style: $0;" "lis" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lis" nil nil)
                       ("lh" "line-height: $0;" "lh" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/lh" nil nil)
                       ("l:a" "left: auto;" "l:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/l_a" nil nil)
                       ("l" "left: $0;" "l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/l" nil nil)
                       ("h:a" "height: auto;" "h:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/h_a" nil nil)
                       ("h" "height: $0;" "h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/h" nil nil)
                       ("fza:n" "font-size-adjust: none;" "fza:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fza_n" nil nil)
                       ("fza" "font-size-adjust: $0;" "fza" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fza" nil nil)
                       ("fz" "font-size: $0;" "fz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fz" nil nil)
                       ("fw:n" "font-weight: normal;" "fw:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fw_n" nil nil)
                       ("fw:lr" "font-weight: lighter;" "fw:lr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fw_lr" nil nil)
                       ("fw:br" "font-weight: bolder;" "fw:br" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fw_br" nil nil)
                       ("fw:b" "font-weight: bold;" "fw:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fw_b" nil nil)
                       ("fw" "font-weight: $0;" "fw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fw" nil nil)
                       ("fv:sc" "font-variant: small-caps;" "fv:sc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fv_sc" nil nil)
                       ("fv:n" "font-variant: normal;" "fv:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fv_n" nil nil)
                       ("fv" "font-variant: $0;" "fv" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fv" nil nil)
                       ("fst:ue" "font-stretch: ultra-expanded;" "fst:ue" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_ue" nil nil)
                       ("fst:uc" "font-stretch: ultra-condensed;" "fst:uc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_uc" nil nil)
                       ("fst:se" "font-stretch: semi-expanded;" "fst:se" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_se" nil nil)
                       ("fst:sc" "font-stretch: semi-condensed;" "fst:sc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_sc" nil nil)
                       ("fst:n" "font-stretch: normal;" "fst:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_n" nil nil)
                       ("fst:ee" "font-stretch: extra-expanded;" "fst:ee" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_ee" nil nil)
                       ("fst:ec" "font-stretch: extra-condensed;" "fst:ec" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_ec" nil nil)
                       ("fst:e" "font-stretch: expanded;" "fst:e" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_e" nil nil)
                       ("fst:c" "font-stretch: condensed;" "fst:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst_c" nil nil)
                       ("fst" "font-stretch: $0;" "fst" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fst" nil nil)
                       ("fsm:n" "font-smooth: never;" "fsm:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fsm_n" nil nil)
                       ("fsm:aw" "font-smooth: always;" "fsm:aw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fsm_aw" nil nil)
                       ("fsm:a" "font-smooth: auto;" "fsm:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fsm_a" nil nil)
                       ("fsm" "font-smooth: $0;" "fsm" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fsm" nil nil)
                       ("fs:o" "font-style: oblique;" "fs:o" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fs_o" nil nil)
                       ("fs:n" "font-style: normal;" "fs:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fs_n" nil nil)
                       ("fs:i" "font-style: italic;" "fs:i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fs_i" nil nil)
                       ("fs" "font-style: $0;" "fs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fs" nil nil)
                       ("fl:r" "float: right;" "fl:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fl_r" nil nil)
                       ("fl:n" "float: none;" "fl:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fl_n" nil nil)
                       ("fl:l" "float: left;" "fl:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fl_l" nil nil)
                       ("fl" "float: $0;" "fl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fl" nil nil)
                       ("ff:ss" "font-family: ${0:Helvetica,Arial},sans-serif;" "ff:ss" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ff_ss" nil nil)
                       ("ff:s" "font-family: ${0:Georgia,'Times New Roman'},serif;" "ff:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ff_s" nil nil)
                       ("ff:m" "font-family: ${0:Monaco,'Courier New'},monospace;" "ff:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ff_m" nil nil)
                       ("ff:f" "font-family: ${0:Capitals,Impact},fantasy;" "ff:f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ff_f" nil nil)
                       ("ff:c" "font-family: ${0:'Monotype Corsiva','Comic Sans MS'},cursive;" "ff:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ff_c" nil nil)
                       ("ff" "font-family: $0;" "ff" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ff" nil nil)
                       ("fems:n" "font-emphasize-style: none;" "fems:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fems_n" nil nil)
                       ("fems:dt" "font-emphasize-style: dot;" "fems:dt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fems_dt" nil nil)
                       ("fems:ds" "font-emphasize-style: disc;" "fems:ds" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fems_ds" nil nil)
                       ("fems:c" "font-emphasize-style: circle;" "fems:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fems_c" nil nil)
                       ("fems:ac" "font-emphasize-style: accent;" "fems:ac" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fems_ac" nil nil)
                       ("fems" "font-emphasize-style: $0;" "fems" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fems" nil nil)
                       ("femp:b" "font-emphasize-position: before;" "femp:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/femp_b" nil nil)
                       ("femp:a" "font-emphasize-position: after;" "femp:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/femp_a" nil nil)
                       ("femp" "font-emphasize-position: $0;" "femp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/femp" nil nil)
                       ("fem" "font-emphasize: $0;" "fem" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fem" nil nil)
                       ("fef:o" "font-effect: outline;" "fef:o" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fef_o" nil nil)
                       ("fef:n" "font-effect: none;" "fef:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fef_n" nil nil)
                       ("fef:eg" "font-effect: engrave;" "fef:eg" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fef_eg" nil nil)
                       ("fef:eb" "font-effect: emboss;" "fef:eb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fef_eb" nil nil)
                       ("fef" "font-effect: $0;" "fef" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/fef" nil nil)
                       ("f+" "font: ${1:1em} ${2:Arial},${0:sans-serif};" "f+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/f+" nil nil)
                       ("f" "font: $0;" "f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/f" nil nil)
                       ("exp" "expression()" "exp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/exp" nil nil)
                       ("ec:s" "empty-cells: show;" "ec:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ec_s" nil nil)
                       ("ec:h" "empty-cells: hide;" "ec:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ec_h" nil nil)
                       ("ec" "empty-cells: $0;" "ec" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ec" nil nil)
                       ("d:tbrg" "display: table-row-group;" "d:tbrg" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbrg" nil nil)
                       ("d:tbr" "display: table-row;" "d:tbr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbr" nil nil)
                       ("d:tbhg" "display: table-header-group;" "d:tbhg" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbhg" nil nil)
                       ("d:tbfg" "display: table-footer-group;" "d:tbfg" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbfg" nil nil)
                       ("d:tbcp" "display: table-caption;" "d:tbcp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbcp" nil nil)
                       ("d:tbclg" "display: table-column-group;" "d:tbclg" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbclg" nil nil)
                       ("d:tbcl" "display: table-column;" "d:tbcl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbcl" nil nil)
                       ("d:tbc" "display: table-cell;" "d:tbc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tbc" nil nil)
                       ("d:tb" "display: table;" "d:tb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_tb" nil nil)
                       ("d:ri" "display: run-in;" "d:ri" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_ri" nil nil)
                       ("d:n" "display: none;" "d:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_n" nil nil)
                       ("d:mis" "display: -moz-inline-stack;" "d:mis" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_mis" nil nil)
                       ("d:mib" "display: -moz-inline-box;" "d:mib" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_mib" nil nil)
                       ("d:li" "display: list-item;" "d:li" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_li" nil nil)
                       ("d:itb" "display: inline-table;" "d:itb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_itb" nil nil)
                       ("d:ib" "display: inline-block;" "d:ib" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_ib" nil nil)
                       ("d:i" "display: inline;" "d:i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_i" nil nil)
                       ("d:cp" "display: compact;" "d:cp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_cp" nil nil)
                       ("d:b" "display: block;" "d:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d_b" nil nil)
                       ("d" "display: $0;" "d" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/d" nil nil)
                       ("cur:t" "cursor: text;" "cur:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_t" nil nil)
                       ("cur:p" "cursor: pointer;" "cur:p" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_p" nil nil)
                       ("cur:m" "cursor: move;" "cur:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_m" nil nil)
                       ("cur:he" "cursor: help;" "cur:he" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_he" nil nil)
                       ("cur:ha" "cursor: hand;" "cur:ha" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_ha" nil nil)
                       ("cur:d" "cursor: default;" "cur:d" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_d" nil nil)
                       ("cur:c" "cursor: crosshair;" "cur:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_c" nil nil)
                       ("cur:a" "cursor: auto;" "cur:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur_a" nil nil)
                       ("cur" "cursor: $0;" "cur" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cur" nil nil)
                       ("ct:oq" "content: open-quote;" "ct:oq" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_oq" nil nil)
                       ("ct:noq" "content: no-open-quote;" "ct:noq" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_noq" nil nil)
                       ("ct:ncq" "content: no-close-quote;" "ct:ncq" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_ncq" nil nil)
                       ("ct:n" "content: normal;" "ct:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_n" nil nil)
                       ("ct:cs" "content: counters($0);" "ct:cs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_cs" nil nil)
                       ("ct:cq" "content: close-quote;" "ct:cq" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_cq" nil nil)
                       ("ct:c" "content: counter($0);" "ct:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_c" nil nil)
                       ("ct:a" "content: attr($0);" "ct:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct_a" nil nil)
                       ("ct" "content: $0;" "ct" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/ct" nil nil)
                       ("cps:t" "caption-side: top;" "cps:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cps_t" nil nil)
                       ("cps:b" "caption-side: bottom;" "cps:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cps_b" nil nil)
                       ("cps" "caption-side: $0;" "cps" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cps" nil nil)
                       ("cp:r" "clip: rect(${1:0} ${2:0} ${3:0} ${0:0});" "cp:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cp_r" nil nil)
                       ("cp:a" "clip: auto;" "cp:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cp_a" nil nil)
                       ("cp" "clip: $0;" "cp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cp" nil nil)
                       ("cor" "counter-reset: $0;" "cor" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cor" nil nil)
                       ("coi" "counter-increment: $0;" "coi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/coi" nil nil)
                       ("cl:r" "clear: right;" "cl:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cl_r" nil nil)
                       ("cl:n" "clear: none;" "cl:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cl_n" nil nil)
                       ("cl:l" "clear: left;" "cl:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cl_l" nil nil)
                       ("cl:b" "clear: both;" "cl:b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cl_b" nil nil)
                       ("cl" "clear: $0;" "cl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/cl" nil nil)
                       ("c" "color: #${0:000};" "c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/c" nil nil)
                       ("bxz:cb" "box-sizing: content-box;" "bxz:cb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxz_cb" nil nil)
                       ("bxz:bb" "box-sizing: border-box;" "bxz:bb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxz_bb" nil nil)
                       ("bxz" "box-sizing: $0;" "bxz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxz" nil nil)
                       ("bxsh:w+" "-webkit-box-shadow: ${1:0} ${2:0} ${3:0} #${0:000};" "bxsh:w+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh_w+" nil nil)
                       ("bxsh:w" "-webkit-box-shadow: $0;" "bxsh:w" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh_w" nil nil)
                       ("bxsh:n" "box-shadow: none;" "bxsh:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh_n" nil nil)
                       ("bxsh:m+" "-moz-box-shadow: ${1:0} ${2:0} ${3:0} #${0:000};" "bxsh:m+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh_m+" nil nil)
                       ("bxsh:m" "-moz-box-shadow: $0;" "bxsh:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh_m" nil nil)
                       ("bxsh+" "box-shadow: ${1:0} ${2:0} ${3:0} #${0:000};" "bxsh+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh+" nil nil)
                       ("bxsh" "box-shadow: $0;" "bxsh" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bxsh" nil nil)
                       ("bgz:cv" "background-size: cover;" "bgz:cv" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgz_cv" nil nil)
                       ("bgz:ct" "background-size: contain;" "bgz:ct" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgz_ct" nil nil)
                       ("bgz:a" "background-size: auto;" "bgz:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgz_a" nil nil)
                       ("bgz" "background-size: $0;" "bgz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgz" nil nil)
                       ("bgr:y" "background-repeat: repeat-y;" "bgr:y" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgr_y" nil nil)
                       ("bgr:x" "background-repeat: repeat-x;" "bgr:x" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgr_x" nil nil)
                       ("bgr:r" "background-repeat: repeat;" "bgr:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgr_r" nil nil)
                       ("bgr:n" "background-repeat: no-repeat;" "bgr:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgr_n" nil nil)
                       ("bgr" "background-repeat: $0;" "bgr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgr" nil nil)
                       ("bgpy" "background-position-y: $0;" "bgpy" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgpy" nil nil)
                       ("bgpx" "background-position-x: $0;" "bgpx" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgpx" nil nil)
                       ("bgp" "background-position: ${1:0} ${0:0};" "bgp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgp" nil nil)
                       ("bgo:pb" "background-origin: padding-box;" "bgo:pb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgo_pb" nil nil)
                       ("bgo:cb" "background-origin: content-box;" "bgo:cb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgo_cb" nil nil)
                       ("bgo:bb" "background-origin: border-box;" "bgo:bb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgo_bb" nil nil)
                       ("bgo" "background-origin: $0;" "bgo" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgo" nil nil)
                       ("bgi:n" "background-image: none;" "bgi:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgi_n" nil nil)
                       ("bgi" "background-image: url($0);" "bgi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgi" nil nil)
                       ("bgcp:pb" "background-clip: padding-box;" "bgcp:pb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgcp_pb" nil nil)
                       ("bgcp:nc" "background-clip: no-clip;" "bgcp:nc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgcp_nc" nil nil)
                       ("bgcp:cb" "background-clip: content-box;" "bgcp:cb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgcp_cb" nil nil)
                       ("bgcp:bb" "background-clip: border-box;" "bgcp:bb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgcp_bb" nil nil)
                       ("bgcp" "background-clip: $0;" "bgcp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgcp" nil nil)
                       ("bgc:t" "background-color: transparent;" "bgc:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgc_t" nil nil)
                       ("bgc" "background-color: #${0:FFF};" "bgc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgc" nil nil)
                       ("bgbk:eb" "background-break: each-box;" "bgbk:eb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgbk_eb" nil nil)
                       ("bgbk:c" "background-break: continuous;" "bgbk:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgbk_c" nil nil)
                       ("bgbk:bb" "background-break: bounding-box;" "bgbk:bb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgbk_bb" nil nil)
                       ("bgbk" "background-break: $0;" "bgbk" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bgbk" nil nil)
                       ("bga:s" "background-attachment: scroll;" "bga:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bga_s" nil nil)
                       ("bga:f" "background-attachment: fixed;" "bga:f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bga_f" nil nil)
                       ("bga" "background-attachment: $0;" "bga" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bga" nil nil)
                       ("bg:n" "background: none;" "bg:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bg_n" nil nil)
                       ("bg:ie" "filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='$1',sizingMethod='${0:crop}');" "bg:ie" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bg_ie" nil nil)
                       ("bg+" "background: #${1:FFF} url($2) ${3:0} ${4:0} ${0:no-repeat};" "bg+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bg+" nil nil)
                       ("bg" "background: $0;" "bg" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bg" nil nil)
                       ("bdw" "border-width: $0;" "bdw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdw" nil nil)
                       ("bdtw" "border-top-width: $0;" "bdtw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtw" nil nil)
                       ("bdts:n" "border-top-style: none;" "bdts:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdts_n" nil nil)
                       ("bdts" "border-top-style: $0;" "bdts" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdts" nil nil)
                       ("bdtrrz" "border-top-right-radius: $0;" "bdtrrz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtrrz" nil nil)
                       ("bdtri:n" "border-top-right-image: none;" "bdtri:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtri_n" nil nil)
                       ("bdtri:c" "border-top-right-image: continue;" "bdtri:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtri_c" nil nil)
                       ("bdtri" "border-top-right-image: url($0);" "bdtri" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtri" nil nil)
                       ("bdtlrz" "border-top-left-radius: $0;" "bdtlrz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtlrz" nil nil)
                       ("bdtli:n" "border-corner-image: none;" "bdtli:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtli_n" nil nil)
                       ("bdtli:c" "border-corner-image: continue;" "bdtli:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtli_c" nil nil)
                       ("bdtli" "border-top-left-image: url($0);" "bdtli" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtli" nil nil)
                       ("bdti:n" "border-top-image: none;" "bdti:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdti_n" nil nil)
                       ("bdti" "border-top-image: url($0);" "bdti" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdti" nil nil)
                       ("bdtc" "border-top-color: #${0:000};" "bdtc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdtc" nil nil)
                       ("bdt:n" "border-top: none;" "bdt:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdt_n" nil nil)
                       ("bdt+" "border-top: ${1:1px} ${2:solid} #${0:000};" "bdt+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdt+" nil nil)
                       ("bdt" "border-top: $0;" "bdt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdt" nil nil)
                       ("bdsp" "border-spacing: $0;" "bdsp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdsp" nil nil)
                       ("bds:w" "border-style: wave;" "bds:w" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_w" nil nil)
                       ("bds:s" "border-style: solid;" "bds:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_s" nil nil)
                       ("bds:r" "border-style: ridge;" "bds:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_r" nil nil)
                       ("bds:o" "border-style: outset;" "bds:o" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_o" nil nil)
                       ("bds:n" "border-style: none;" "bds:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_n" nil nil)
                       ("bds:i" "border-style: inset;" "bds:i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_i" nil nil)
                       ("bds:h" "border-style: hidden;" "bds:h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_h" nil nil)
                       ("bds:g" "border-style: groove;" "bds:g" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_g" nil nil)
                       ("bds:dtdtds" "border-style: dot-dot-dash;" "bds:dtdtds" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_dtdtds" nil nil)
                       ("bds:dtds" "border-style: dot-dash;" "bds:dtds" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_dtds" nil nil)
                       ("bds:dt" "border-style: dotted;" "bds:dt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_dt" nil nil)
                       ("bds:ds" "border-style: dashed;" "bds:ds" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_ds" nil nil)
                       ("bds:db" "border-style: double;" "bds:db" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds_db" nil nil)
                       ("bds" "border-style: $0;" "bds" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bds" nil nil)
                       ("bdrz:w" "-webkit-border-radius: $0;" "bdrz:w" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrz_w" nil nil)
                       ("bdrz:m" "-moz-border-radius: $0;" "bdrz:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrz_m" nil nil)
                       ("bdrz" "border-radius: $0;" "bdrz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrz" nil nil)
                       ("bdrw" "border-right-width: $0;" "bdrw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrw" nil nil)
                       ("bdrs:n" "border-right-style: none;" "bdrs:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrs_n" nil nil)
                       ("bdrs" "border-right-style: $0;" "bdrs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrs" nil nil)
                       ("bdri:n" "border-right-image: none;" "bdri:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdri_n" nil nil)
                       ("bdri" "border-right-image: url($0);" "bdri" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdri" nil nil)
                       ("bdrc" "border-right-color: #${0:000};" "bdrc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdrc" nil nil)
                       ("bdr:n" "border-right: none;" "bdr:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdr_n" nil nil)
                       ("bdr+" "border-right: ${1:1px} ${2:solid} #${0:000};" "bdr+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdr+" nil nil)
                       ("bdr" "border-right: $0;" "bdr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdr" nil nil)
                       ("bdlw" "border-left-width: $0;" "bdlw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdlw" nil nil)
                       ("bdlt:a" "border-length: auto;" "bdlt:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdlt_a" nil nil)
                       ("bdlt" "border-length: $0;" "bdlt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdlt" nil nil)
                       ("bdls:n" "border-left-style: none;" "bdls:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdls_n" nil nil)
                       ("bdls" "border-left-style: $0;" "bdls" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdls" nil nil)
                       ("bdli:n" "border-left-image: none;" "bdli:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdli_n" nil nil)
                       ("bdli" "border-left-image: url($0);" "bdli" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdli" nil nil)
                       ("bdlc" "border-left-color: #${0:000};" "bdlc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdlc" nil nil)
                       ("bdl:n" "border-left: none;" "bdl:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdl_n" nil nil)
                       ("bdl+" "border-left: ${1:1px} ${2:solid} #${0:000};" "bdl+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdl+" nil nil)
                       ("bdl" "border-left: $0;" "bdl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdl" nil nil)
                       ("bdi:w+" "-webkit-border-image: url($1) ${2:0} ${3:0} ${4:0} ${5:0} ${6:stretch} ${0:stretch};" "bdi:w+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdi_w+" nil nil)
                       ("bdi:w" "-webkit-border-image: $0;" "bdi:w" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdi_w" nil nil)
                       ("bdi:n" "border-image: none;" "bdi:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdi_n" nil nil)
                       ("bdi:m+" "-moz-border-image: url($1) ${2:0} ${3:0} ${4:0} ${5:0} ${6:stretch} ${0:stretch};" "bdi:m+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdi_m+" nil nil)
                       ("bdi:m" "-moz-border-image: $0;" "bdi:m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdi_m" nil nil)
                       ("bdi" "border-image: url($1) ${2:0} ${3:0} ${4:0} ${5:0} ${6:stretch} ${0:stretch};" "bdi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdi" nil nil)
                       ("bdf:st" "border-fit: stretch;" "bdf:st" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_st" nil nil)
                       ("bdf:sp" "border-fit: space;" "bdf:sp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_sp" nil nil)
                       ("bdf:sc" "border-fit: scale;" "bdf:sc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_sc" nil nil)
                       ("bdf:r" "border-fit: repeat;" "bdf:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_r" nil nil)
                       ("bdf:ow" "border-fit: overwrite;" "bdf:ow" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_ow" nil nil)
                       ("bdf:of" "border-fit: overwrite;" "bdf:of" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_of" nil nil)
                       ("bdf:c" "border-fit: clip;" "bdf:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf_c" nil nil)
                       ("bdf" "border-fit: $0;" "bdf" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdf" nil nil)
                       ("bdcl:s" "border-collapse: separate;" "bdcl:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdcl_s" nil nil)
                       ("bdcl:c" "border-collapse: collapse;" "bdcl:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdcl_c" nil nil)
                       ("bdcl" "border-collapse: $0;" "bdcl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdcl" nil nil)
                       ("bdci:n" "border-corner-image: none;" "bdci:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdci_n" nil nil)
                       ("bdci:c" "border-corner-image: continue;" "bdci:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdci_c" nil nil)
                       ("bdci" "border-corner-image: url($0);" "bdci" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdci" nil nil)
                       ("bdc" "border-color: #${0:000};" "bdc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdc" nil nil)
                       ("bdbw" "border-bottom-width: $0;" "bdbw" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbw" nil nil)
                       ("bdbs:n" "border-bottom-style: none;" "bdbs:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbs_n" nil nil)
                       ("bdbs" "border-bottom-style: $0;" "bdbs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbs" nil nil)
                       ("bdbrrz" "border-bottom-right-radius: $0;" "bdbrrz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbrrz" nil nil)
                       ("bdbri:n" "border-bottom-right-image: none;" "bdbri:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbri_n" nil nil)
                       ("bdbri:c" "border-bottom-right-image: continue;" "bdbri:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbri_c" nil nil)
                       ("bdbri" "border-bottom-right-image: url($0);" "bdbri" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbri" nil nil)
                       ("bdblrz" "border-bottom-left-radius: $0;" "bdblrz" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdblrz" nil nil)
                       ("bdbli:n" "border-bottom-left-image: none;" "bdbli:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbli_n" nil nil)
                       ("bdbli:c" "border-bottom-left-image: continue;" "bdbli:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbli_c" nil nil)
                       ("bdbli" "border-bottom-left-image: url($0);" "bdbli" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbli" nil nil)
                       ("bdbk:c" "border-break: close;" "bdbk:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbk_c" nil nil)
                       ("bdbk" "border-break: $0;" "bdbk" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbk" nil nil)
                       ("bdbi:n" "border-bottom-image: none;" "bdbi:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbi_n" nil nil)
                       ("bdbi" "border-bottom-image: url($0);" "bdbi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbi" nil nil)
                       ("bdbc" "border-bottom-color: #${0:000};" "bdbc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdbc" nil nil)
                       ("bdb:n" "border-bottom: none;" "bdb:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdb_n" nil nil)
                       ("bdb+" "border-bottom: ${1:1px} ${2:solid} #${0:000};" "bdb+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdb+" nil nil)
                       ("bdb" "border-bottom: $0;" "bdb" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bdb" nil nil)
                       ("bd:n" "border: none;" "bd:n" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bd_n" nil nil)
                       ("bd+" "border: ${1:1px} ${2:solid} #${0:000};" "bd+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bd+" nil nil)
                       ("bd" "border: $0;" "bd" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/bd" nil nil)
                       ("b:a" "bottom: auto;" "b:a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/b_a" nil nil)
                       ("b" "bottom: $0;" "b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/b" nil nil)
                       (":oc" ":only-child" ":oc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_oc" nil nil)
                       (":nlc" ":nth-last-child($0)" ":nlc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_nlc" nil nil)
                       (":nc" ":nth-child($0)" ":nc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_nc" nil nil)
                       (":lc" ":last-child" ":lc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_lc" nil nil)
                       (":h" ":hover" ":h" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_h" nil nil)
                       (":fc" ":first-child" ":fc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_fc" nil nil)
                       (":b" ":before" ":b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_b" nil nil)
                       (":a" ":after" ":a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_a" nil nil)
                       ("::b" "::before" "::b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/__b" nil nil)
                       ("::a" "::after" "::a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/__a" nil nil)
                       ("." "$1 {\n	$0\n}" "." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/_" nil nil)
                       ("@m" "@media ${1:print} {\n	$0\n}" "@m" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/@m" nil nil)
                       ("@i" "@import url($0);" "@i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/@i" nil nil)
                       ("@f" "@font-face {\n	font-family: $1;\n	src: url($0);\n}" "@f" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/@f" nil nil)
                       ("!" "!important" "!" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/css-mode/!" nil nil)))


;;; Do not edit! File generated at Sun Oct 25 17:07:30 2015
