;;; Compiled snippets and support files for `html-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'html-mode
                     '(("xhtml" "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n$0\n</html>" "xhtml" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/xhtml" nil nil)
                       ("width" "width=\"$1\"" "width" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/width" nil nil)
                       ("wbr" "<wbr />" "wbr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/wbr" nil nil)
                       ("video" "<video src=\"$1 height=\"$2\" width=\"$3\" preload=\"${5:none}\" autoplay=\"${6:autoplay}>$7</video>" "video" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/video" nil nil)
                       ("var" "<var>$0</var>" "var" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/var" nil nil)
                       ("value" "value=\"$1\"" "value" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/value" nil nil)
                       ("up" "&#x2191;" "up" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/up" nil nil)
                       ("ul." "<ul class=\"$1\">\n	$0\n</ul>" "ul." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ul." nil nil)
                       ("ul+" "<ul>\n	<li>$1</li>\n	li+$0\n</ul>" "ul+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ul+" nil nil)
                       ("ul#" "<ul id=\"$1\">\n	$0\n</ul>" "ul#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ul#" nil nil)
                       ("ul" "<ul>\n	$0\n</ul>" "ul" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ul" nil nil)
                       ("type" "type=\"$1\"" "type" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/type" nil nil)
                       ("track" "<track src=\"$1\" srclang=\"$2\" label=\"$3\" default=\"${4:default}>$5</track>" "track" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/track" nil nil)
                       ("tr+" "<tr>\n	<td>$1</td>\n	td+$0\n</tr>" "tr+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/tr+" nil nil)
                       ("tr" "<tr>\n	$0\n</tr>" "tr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/tr" nil nil)
                       ("title=" "title=\"$1\"" "title=" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/title=" nil nil)
                       ("title" "<title>${0:`(file-name-base)`}</title>" "title" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/title" nil nil)
                       ("time" "<time datetime=\"$1\" pubdate=\"${2:$1}\">${0:$1}</time>" "time" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/time" nil nil)
                       ("thead" "<thead>\n	$0\n</thead>" "thead" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/thead" nil nil)
                       ("th." "<th class=\"$1\">$0</th>" "th." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/th." nil nil)
                       ("th+" "<th>$1</th>\nth+$0" "th+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/th+" nil nil)
                       ("th#" "<th id=\"$1\">$0</th>" "th#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/th#" nil nil)
                       ("th" "<th>$0</th>" "th" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/th" nil nil)
                       ("tfoot" "<tfoot>\n	$0\n</tfoot>" "tfoot" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/tfoot" nil nil)
                       ("textarea" "<textarea name=\"$1\" id=\"${2:$1}\" rows=\"${3:8}\" cols=\"${4:40}\">$5</textarea>" "textarea" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/textarea" nil nil)
                       ("td." "<td class=\"$1\">$0</td>" "td." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/td." nil nil)
                       ("td+" "<td>$1</td>\ntd+$0" "td+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/td+" nil nil)
                       ("td#" "<td id=\"$1\">$0</td>" "td#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/td#" nil nil)
                       ("td" "<td>$0</td>" "td" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/td" nil nil)
                       ("tbody" "<tbody>\n	$0\n</tbody>" "tbody" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/tbody" nil nil)
                       ("table." "<table class=\"$1\">\n	$0\n</table>" "table." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/table." nil nil)
                       ("table#" "<table id=\"$1\">\n	$0\n</table>" "table#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/table#" nil nil)
                       ("table" "<table>\n	$0\n</table>" "table" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/table" nil nil)
                       ("tab" "&#x21E5;" "tab" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/tab" nil nil)
                       ("sup" "<sup>$0</sup>" "sup" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/sup" nil nil)
                       ("summary" "<summary>\n	$0\n</summary>" "summary" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/summary" nil nil)
                       ("sub" "<sub>$0</sub>" "sub" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/sub" nil nil)
                       ("style" "<style type=\"text/css\" media=\"${1:all}\">\n	$0\n</style>" "style" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/style" nil nil)
                       ("strong" "<strong>$0</strong>" "strong" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/strong" nil nil)
                       ("src" "src=\"$1\"" "src" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/src" nil nil)
                       ("span." "<span class=\"$1\">$0</span>" "span." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/span." nil nil)
                       ("span#" "<span id=\"$1\">$0</span>" "span#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/span#" nil nil)
                       ("span" "<span>$0</span>" "span" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/span" nil nil)
                       ("source" "<source src=\"$1\" type=\"$2\" media=\"$0\" />" "source" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/source" nil nil)
                       ("small" "<small>$0</small>" "small" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/small" nil nil)
                       ("shift" "&#x21E7;" "shift" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/shift" nil nil)
                       ("select." "<select name=\"$1\" id=\"${2:$1}\" class=\"$3>\n	$0\n</select>" "select." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/select." nil nil)
                       ("select+" "<select name=\"$1\" id=\"${2:$1}\">\n	<option value=\"$3\">${4:$3}</option>\n	opt+$0\n</select>" "select+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/select+" nil nil)
                       ("select" "<select name=\"$1\" id=\"${2:$1}\">\n	$0\n</select>" "select" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/select" nil nil)
                       ("section." "<section class=\"$1\">\n	$0\n</section>" "section." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/section." nil nil)
                       ("section#" "<section id=\"$1\">\n	$0\n</section>" "section#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/section#" nil nil)
                       ("section" "<section>\n	$0\n</section>" "section" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/section" nil nil)
                       ("scriptt" "<script type=\"$1\" id=\"$2\">\n	$0\n</script>" "scriptt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/scriptt" nil nil)
                       ("scriptsrc" "<script src=\"$0.js\" type=\"text/javascript\" charset=\"utf-8\"></script>" "scriptsrc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/scriptsrc" nil nil)
                       ("scripts" "<script src=\"$0.js\"></script>" "scripts" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/scripts" nil nil)
                       ("script" "<script type=\"text/javascript\" charset=\"utf-8\">\n	$0\n</script>" "script" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/script" nil nil)
                       ("scope" "scope=\"${1:row}\"" "scope" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/scope" nil nil)
                       ("samp" "<samp>\n	$0\n</samp>" "samp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/samp" nil nil)
                       ("s" "<s>$0</s>" "s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/s" nil nil)
                       ("ruby" "<ruby>\n	<rp><rt>$0</rt></rp>\n</ruby>" "ruby" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ruby" nil nil)
                       ("rt" "<rt>$0</rt>" "rt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/rt" nil nil)
                       ("rp" "<rp>$0</rp>" "rp" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/rp" nil nil)
                       ("right" "&#x2192;" "right" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/right" nil nil)
                       ("return" "&#x21A9;" "return" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/return" nil nil)
                       ("rel" "rel=\"$1\"" "rel" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/rel" nil nil)
                       ("q" "<q>$0</q>" "q" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/q" nil nil)
                       ("progress" "<progress>$0</progress>" "progress" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/progress" nil nil)
                       ("pre" "<pre>\n	$0\n</pre>" "pre" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/pre" nil nil)
                       ("param" "<param name=\"$1\" value=\"$2\" />" "param" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/param" nil nil)
                       ("p." "<p class=\"$1\">$0</p>" "p." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/p." nil nil)
                       ("p#" "<p id=\"$1\">$0</p>" "p#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/p#" nil nil)
                       ("p" "<p>$0</p>" "p" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/p" nil nil)
                       ("output" "<output>$0</output>" "output" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/output" nil nil)
                       ("optt" "<option>$0</option>" "optt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/optt" nil nil)
                       ("option" "&#x2325;" "option" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/option" nil nil)
                       ("optgroup" "<optgroup>\n	<option value=\"$1\">${2:$1}</option>\n	opt+$0\n</optgroup>" "optgroup" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/optgroup" nil nil)
                       ("opt+" "<option value=\"$1\">${2:$1}</option>\nopt+$0" "opt+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/opt+" nil nil)
                       ("opt" "<option value=\"$1\">${0:$1}</option>" "opt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/opt" nil nil)
                       ("ol." "<ol class=\"$1\">\n	$0\n</ol>" "ol." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ol." nil nil)
                       ("ol+" "<ol>\n	<li>$1</li>\n	li+$0\n</ol>" "ol+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ol+" nil nil)
                       ("ol#" "<ol id=\"$1\">\n	$0\n</ol>" "ol#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ol#" nil nil)
                       ("ol" "<ol>\n	$0\n</ol>" "ol" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ol" nil nil)
                       ("object" "<object data=\"$1\" type=\"$2\">\n	$3\n</object>" "object" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/object" nil nil)
                       ("noscript" "<noscript>\n	$0\n</noscript>" "noscript" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/noscript" nil nil)
                       ("nbs" "&nbsp;" "nbs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/nbs" nil nil)
                       ("nav." "<nav class=\"$1\">\n	$0\n</nav>" "nav." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/nav." nil nil)
                       ("nav#" "<nav id=\"$1\">\n	$0\n</nav>" "nav#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/nav#" nil nil)
                       ("nav" "<nav>\n	$0\n</nav>" "nav" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/nav" nil nil)
                       ("name" "name=\"$1\"" "name" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/name" nil nil)
                       ("movie" "<object width=\"$2\" height=\"$3\" classid=\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\"\ncodebase=\"http://www.apple.com/qtactivex/qtplugin.cab\">\n	<param name=\"src\" value=\"$1\" />\n	<param name=\"controller\" value=\"$4\" />\n	<param name=\"autoplay\" value=\"$5\" />\n	<embed src=\"${1:movie.mov}\"\n		width=\"${2:320}\" height=\"${3:240}\"\n		controller=\"${4:true}\" autoplay=\"${5:true}\"\n		scale=\"tofit\" cache=\"true\"\n		pluginspage=\"http://www.apple.com/quicktime/download/\" />\n</object>" "movie" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/movie" nil nil)
                       ("meter" "<meter>$0</meter>" "meter" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meter" nil nil)
                       ("meta:utf" "<meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" />" "meta:utf" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meta_utf" nil nil)
                       ("meta:s" "<meta $0 />" "meta:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meta_s" nil nil)
                       ("meta:refresh" "<meta http-equiv=\"refresh\" content=\"text/html;charset=UTF-8\" />" "meta:refresh" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meta_refresh" nil nil)
                       ("meta:d" "<meta name=\"description\" content=\"$0\" />" "meta:d" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meta_d" nil nil)
                       ("meta:compat" "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=${1:7,8,edge}\" />" "meta:compat" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meta_compat" nil nil)
                       ("meta" "<meta http-equiv=\"$1\" content=\"$2\" />" "meta" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/meta" nil nil)
                       ("menu:t" "<menu type=\"toolbar\">\n	$0\n</menu>" "menu:t" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/menu_t" nil nil)
                       ("menu:c" "<menu type=\"context\">\n	$0\n</menu>" "menu:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/menu_c" nil nil)
                       ("menu" "<menu>\n	$0\n</menu>" "menu" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/menu" nil nil)
                       ("media" "media=\"$1\"" "media" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/media" nil nil)
                       ("mark" "<mark>$0</mark>" "mark" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/mark" nil nil)
                       ("map." "<map class=\"$1\" name=\"$2\">\n	$0\n</map>" "map." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/map." nil nil)
                       ("map+" "<map name=\"$1\">\n	<area shape=\"$2\" coords=\"$3\" href=\"$4\" alt=\"$5\" />$6\n</map>" "map+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/map+" nil nil)
                       ("map#" "<map name=\"$1\" id=\"${2:$1}>\n	$0\n</map>" "map#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/map#" nil nil)
                       ("map" "<map name=\"$1\">\n	$0\n</map>" "map" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/map" nil nil)
                       ("main" "<main role=\"main\">\n	$0\n</main>" "main" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/main" nil nil)
                       ("link:touch" "<link rel=\"apple-touch-icon\" href=\"${1:favicon.png}\" />" "link:touch" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link_touch" nil nil)
                       ("link:s" "<link rel=\"stylesheet\" href=\"${1:style.css}\" />" "link:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link_s" nil nil)
                       ("link:rss" "<link rel=\"alternate\" href=\"${1:rss.xml}\" title=\"RSS\" type=\"application/atom+xml\" />" "link:rss" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link_rss" nil nil)
                       ("link:favicon" "<link rel=\"shortcut icon\" href=\"${1:favicon.ico}\" type=\"image/x-icon\" />" "link:favicon" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link_favicon" nil nil)
                       ("link:css" "<link rel=\"stylesheet\" href=\"${1:style.css}\" type=\"text/css\" media=\"${2:all}\" />" "link:css" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link_css" nil nil)
                       ("link:atom" "<link rel=\"alternate\" href=\"${1:atom.xml}\" title=\"Atom\" type=\"application/atom+xml\" />" "link:atom" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link_atom" nil nil)
                       ("link" "<link rel=\"$1\" href=\"$2\" title=\"$3\" type=\"$4\" />" "link" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/link" nil nil)
                       ("lia+" "<li><a href=\"${2:#}\">$1</a></li>\nlia+" "lia+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/lia+" nil nil)
                       ("lia" "<li><a href=\"${0:#}\">$1</a></li>" "lia" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/lia" nil nil)
                       ("li." "<li class=\"$1\">$0</li>" "li." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/li." nil nil)
                       ("li+" "<li>$1</li>\nli+" "li+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/li+" nil nil)
                       ("li" "<li>$0</li>" "li" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/li" nil nil)
                       ("legend+" "<legend><span>$0</span></legend>" "legend+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/legend+" nil nil)
                       ("legend" "<legend>$0</legend>" "legend" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/legend" nil nil)
                       ("left" "&#x2190;" "left" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/left" nil nil)
                       ("lang" "lang=\"${1:en}\"" "lang" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/lang" nil nil)
                       ("label:s" "<label for=\"${2:$1}\">$1</label>\n<select name=\"${3:$2}\" id=\"${4:$2}\">\n	<option value=\"$5\">${0:$5}</option>\n</select>" "label:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/label_s" nil nil)
                       ("label:i" "<label for=\"${2:$1}\">$1</label>\n<input type=\"${3:text/submit/hidden/button}\" name=\"${4:$2}\" id=\"${5:$2}\" value=\"$6\" />" "label:i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/label_i" nil nil)
                       ("label" "<label for=\"${0:$1}\">$1</label>" "label" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/label" nil nil)
                       ("keygen" "<keygen>$0</keygen>" "keygen" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/keygen" nil nil)
                       ("kbd" "<kbd>$0</kbd>" "kbd" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/kbd" nil nil)
                       ("ins" "<ins>$0</ins>" "ins" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ins" nil nil)
                       ("input:week" "<input type=\"week\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:week" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_week" nil nil)
                       ("input:url" "<input type=\"url\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:url" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_url" nil nil)
                       ("input:time" "<input type=\"time\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:time" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_time" nil nil)
                       ("input:text" "<input type=\"text\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:text" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_text" nil nil)
                       ("input:submit" "<input type=\"submit\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:submit" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_submit" nil nil)
                       ("input:search" "<input type=\"search\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:search" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_search" nil nil)
                       ("input:reset" "<input type=\"reset\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:reset" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_reset" nil nil)
                       ("input:range" "<input type=\"range\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:range" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_range" nil nil)
                       ("input:radio" "<input type=\"radio\" name=\"$1\" id=\"${2:$1}\" />" "input:radio" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_radio" nil nil)
                       ("input:password" "<input type=\"password\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:password" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_password" nil nil)
                       ("input:number" "<input type=\"number\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:number" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_number" nil nil)
                       ("input:month" "<input type=\"month\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:month" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_month" nil nil)
                       ("input:image" "<input type=\"image\" name=\"$1\" id=\"${2:$1}\" src=\"$3\" alt=\"$4\" />" "input:image" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_image" nil nil)
                       ("input:hidden" "<input type=\"hidden\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:hidden" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_hidden" nil nil)
                       ("input:file" "<input type=\"file\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:file" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_file" nil nil)
                       ("input:email" "<input type=\"email\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:email" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_email" nil nil)
                       ("input:datetime-local" "<input type=\"datetime-local\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:datetime-local" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_datetime-local" nil nil)
                       ("input:datetime" "<input type=\"datetime\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:datetime" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_datetime" nil nil)
                       ("input:date" "<input type=\"date\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:date" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_date" nil nil)
                       ("input:color" "<input type=\"color\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:color" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_color" nil nil)
                       ("input:checkbox" "<input type=\"checkbox\" name=\"$1\" id=\"${2:$1}\" />" "input:checkbox" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_checkbox" nil nil)
                       ("input:button" "<input type=\"button\" name=\"$1\" id=\"${2:$1}\" value=\"$3\" />" "input:button" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input_button" nil nil)
                       ("input." "<input class=\"$1\" type=\"${2:text/submit/hidden/button/image}\" name=\"$3\" id=\"${4:$3}\" value=\"$5\" />" "input." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input." nil nil)
                       ("input" "<input type=\"${1:text/submit/hidden/button/image}\" name=\"$2\" id=\"${3:$2}\" value=\"$4\" />" "input" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/input" nil nil)
                       ("img." "<img class=\"$1\" src=\"$2\" alt=\"$3\" />" "img." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/img." nil nil)
                       ("img#" "<img id=\"$1\" src=\"$2\" alt=\"$3\" />" "img#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/img#" nil nil)
                       ("img" "<img src=\"$1\" alt=\"$2\" />" "img" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/img" nil nil)
                       ("iframe." "<iframe class=\"$1\" src=\"$2\" frameborder=\"0\"></iframe>" "iframe." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/iframe." nil nil)
                       ("iframe#" "<iframe id=\"$1\" src=\"$2\" frameborder=\"0\"></iframe>" "iframe#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/iframe#" nil nil)
                       ("iframe" "<iframe src=\"$1\" frameborder=\"0\"></iframe>" "iframe" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/iframe" nil nil)
                       ("i" "<i>$0</i>" "i" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/i" nil nil)
                       ("html5l" "<!DOCTYPE html>\n<html lang=\"${1:es}\">\n	<head>\n		<meta charset=\"utf-8\">\n		<meta name=\"viewport\" content=\"width=device-width\">\n		<title>${2:`(file-name-base)`}</title>\n		${3:link}\n	</head>\n	<body>\n		${0:body}\n	</body>\n</html>" "html5l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/html5l" nil nil)
                       ("html5" "<!DOCTYPE html>\n<html>\n	<head>\n		<meta charset=\"utf-8\">\n		<meta name=\"viewport\" content=\"width=device-width\">\n		<title>${1:`(file-name-base)`}</title>\n		${2:link}\n	</head>\n	<body>\n		${0:body}\n	</body>\n</html>" "html5" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/html5" nil nil)
                       ("html" "<html>\n$0\n</html>" "html" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/html" nil nil)
                       ("href" "href=\"${1:#}\"" "href" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/href" nil nil)
                       ("hr" "<hr />" "hr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/hr" nil nil)
                       ("hgroup." "<hgroup class=\"$1>\n	$0\n</hgroup>" "hgroup." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/hgroup." nil nil)
                       ("hgroup" "<hgroup>\n	$0\n</hgroup>" "hgroup" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/hgroup" nil nil)
                       ("height" "height=\"$1\"" "height" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/height" nil nil)
                       ("header." "<header class=\"$1\">\n	$0\n</header>" "header." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/header." nil nil)
                       ("header#" "<header id=\"$1\">\n	$0\n</header>" "header#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/header#" nil nil)
                       ("header" "<header>\n	$0\n</header>" "header" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/header" nil nil)
                       ("head" "<head>\n	<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n\n	<title>${1:`(file-name-base)`}</title>\n	$0\n</head>" "head" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/head" nil nil)
                       ("h6." "<h6 class=\"$1\">$0</h6>" "h6." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h6." nil nil)
                       ("h6#" "<h6 id=\"$1\">$0</h6>" "h6#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h6#" nil nil)
                       ("h6" "<h6>$0</h6>" "h6" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h6" nil nil)
                       ("h5." "<h5 class=\"$1\">$0</h5>" "h5." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h5." nil nil)
                       ("h5#" "<h5 id=\"$1\">$0</h5>" "h5#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h5#" nil nil)
                       ("h5" "<h5>$0</h5>" "h5" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h5" nil nil)
                       ("h4." "<h4 class=\"$1\">$0</h4>" "h4." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h4." nil nil)
                       ("h4#" "<h4 id=\"$1\">$0</h4>" "h4#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h4#" nil nil)
                       ("h4" "<h4>$0</h4>" "h4" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h4" nil nil)
                       ("h3." "<h3 class=\"$1\">$0</h3>" "h3." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h3." nil nil)
                       ("h3#" "<h3 id=\"$1\">$0</h3>" "h3#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h3#" nil nil)
                       ("h3" "<h3>$0</h3>" "h3" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h3" nil nil)
                       ("h2." "<h2 class=\"$1\">$0</h2>" "h2." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h2." nil nil)
                       ("h2#" "<h2 id=\"$1\">$0</h2>" "h2#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h2#" nil nil)
                       ("h2" "<h2>$0</h2>" "h2" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h2" nil nil)
                       ("h1." "<h1 class=\"$1\">$0</h1>" "h1." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h1." nil nil)
                       ("h1#" "<h1 id=\"$1\">$0</h1>" "h1#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h1#" nil nil)
                       ("h1" "<h1>$0</h1>" "h1" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/h1" nil nil)
                       ("form." "<form class=\"$1\" action=\"$2\" method=\"${3:post}\">\n	$0\n</form>" "form." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/form." nil nil)
                       ("form#" "<form id=\"$1\" action=\"$2\" method=\"${3:post}\">\n	$0\n</form>" "form#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/form#" nil nil)
                       ("form" "<form action=\"$1\" method=\"${2:post}\">\n	$0\n</form>" "form" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/form" nil nil)
                       ("for" "for=\"$1\"" "for" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/for" nil nil)
                       ("footer." "<footer class=\"$1\">\n	$0\n</footer>" "footer." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/footer." nil nil)
                       ("footer#" "<footer id=\"$1\">\n	$0\n</footer>" "footer#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/footer#" nil nil)
                       ("footer" "<footer>\n	$0\n</footer>" "footer" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/footer" nil nil)
                       ("figure." "<figure class=\"$1\">\n	$0\n</figure>" "figure." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/figure." nil nil)
                       ("figure#" "<figure id=\"$1\">\n	$0\n</figure>" "figure#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/figure#" nil nil)
                       ("figure" "<figure>$0</figure>" "figure" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/figure" nil nil)
                       ("figcaption" "<figcaption>$0</figcaption>" "figcaption" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/figcaption" nil nil)
                       ("fieldset." "<fieldset class=\"$1\">\n	$0\n</fieldset>" "fieldset." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/fieldset." nil nil)
                       ("fieldset+" "<fieldset>\n	<legend><span>$1</span></legend>\n	$2\n</fieldset>\nfieldset+$0" "fieldset+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/fieldset+" nil nil)
                       ("fieldset#" "<fieldset id=\"$1\">\n	$0\n</fieldset>" "fieldset#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/fieldset#" nil nil)
                       ("fieldset" "<fieldset>\n	$0\n</fieldset>" "fieldset" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/fieldset" nil nil)
                       ("esc" "&#x238B;" "esc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/esc" nil nil)
                       ("enter" "&#x2305;" "enter" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/enter" nil nil)
                       ("embed" "<embed src=\"$1\" type=\"$0\" />" "embed" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/embed" nil nil)
                       ("em" "<em>$0</em>" "em" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/em" nil nil)
                       ("dt." "<dt class=\"$1\">$0</dt>" "dt." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dt." nil nil)
                       ("dt+" "<dt>$1</dt>\n<dd>$2</dd>\ndt+$0" "dt+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dt+" nil nil)
                       ("dt#" "<dt id=\"$1\">$0</dt>" "dt#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dt#" nil nil)
                       ("dt" "<dt>$0</dt>" "dt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dt" nil nil)
                       ("down" "&#x2193;" "down" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/down" nil nil)
                       ("docxt" "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">" "docxt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/docxt" nil nil)
                       ("docxs" "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">" "docxs" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/docxs" nil nil)
                       ("docxf" "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Frameset//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd\">" "docxf" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/docxf" nil nil)
                       ("docx" "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\"\n\"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">" "docx" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/docx" nil nil)
                       ("doctype" "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\"\n\"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">" "XHTML 1.1" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/doctype" nil nil)
                       ("docts" "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\n\"http://www.w3.org/TR/html4/strict.dtd\">" "docts" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/docts" nil nil)
                       ("doct5" "<!DOCTYPE HTML>" "doct5" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/doct5" nil nil)
                       ("doct" "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n\"http://www.w3.org/TR/html4/loose.dtd\">" "doct" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/doct" nil nil)
                       ("dl." "<dl class=\"$1\">\n	$0\n</dl>" "dl." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dl." nil nil)
                       ("dl+" "<dl>\n	<dt>$1</dt>\n	<dd>$2</dd>\n	dt+$0\n</dl>" "dl+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dl+" nil nil)
                       ("dl#" "<dl id=\"$1\">\n	$0\n</dl>" "dl#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dl#" nil nil)
                       ("dl" "<dl>\n	$0\n</dl>" "dl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dl" nil nil)
                       ("div." "<div class=\"$1\">\n	$0\n</div>" "div." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/div." nil nil)
                       ("div#" "<div id=\"$1\">\n	$0\n</div>" "div#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/div#" nil nil)
                       ("div" "<div>\n	$0\n</div>" "div" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/div" nil nil)
                       ("dialog" "<dialog>\n	$0\n</dialog>" "dialog" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dialog" nil nil)
                       ("dfn" "<dfn>$0</dfn>" "dfn" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dfn" nil nil)
                       ("details" "<details>$0</details>" "details" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/details" nil nil)
                       ("delete" "&#x2326;" "delete" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/delete" nil nil)
                       ("del" "<del>$0</del>" "del" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/del" nil nil)
                       ("dd." "<dd class=\"$1\">$0</dd>" "dd." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dd." nil nil)
                       ("dd#" "<dd id=\"$1\">$0</dd>" "dd#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dd#" nil nil)
                       ("dd" "<dd>$0</dd>" "dd" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/dd" nil nil)
                       ("datatemplate" "<datatemplate>\n	$0\n</datatemplate>" "datatemplate" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/datatemplate" nil nil)
                       ("datalist" "<datalist>\n	$0\n</datalist>" "datalist" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/datalist" nil nil)
                       ("datagrid" "<datagrid>\n	$0\n</datagrid>" "datagrid" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/datagrid" nil nil)
                       ("data" "data-$1=\"${2:$1}\"" "data" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/data" nil nil)
                       ("ctrl" "&#x2303;" "ctrl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ctrl" nil nil)
                       ("command:r" "<command type=\"radio\" radiogroup=\"$1\" label=\"$2\" icon=\"$0\" />" "command:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/command_r" nil nil)
                       ("command:c" "<command type=\"checkbox\" label=\"$1\" icon=\"$0\" />" "command:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/command_c" nil nil)
                       ("command" "<command type=\"command\" label=\"$1\" icon=\"$0\" />" "command" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/command" nil nil)
                       ("colgroup+" "<colgroup>\n	<col />\n	col+$0\n</colgroup>" "colgroup+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/colgroup+" nil nil)
                       ("colgroup" "<colgroup>\n	$0\n</colgroup>" "colgroup" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/colgroup" nil nil)
                       ("col+" "<col />\ncol+" "col+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/col+" nil nil)
                       ("col" "<col />" "col" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/col" nil nil)
                       ("code" "<code>$0</code>" "code" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/code" nil nil)
                       ("cmd" "&#x2318;" "cmd" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/cmd" nil nil)
                       ("cite" "<cite>$0</cite>" "cite" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/cite" nil nil)
                       ("charset" "charset=\"${1:utf-8}\"" "charset" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/charset" nil nil)
                       ("caption" "<caption>$0</caption>" "caption" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/caption" nil nil)
                       ("canvas" "<canvas>\n	$0\n</canvas>" "canvas" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/canvas" nil nil)
                       ("button:s" "<button type=\"submit\">$0</button>" "button:s" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/button_s" nil nil)
                       ("button:r" "<button type=\"reset\">$0</button>" "button:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/button_r" nil nil)
                       ("button." "<button class=\"${1:button}\" type=\"${2:submit}\">$0</button>" "button." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/button." nil nil)
                       ("button#" "<button id=\"$1\" type=\"${2:submit}\">$0</button>" "button#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/button#" nil nil)
                       ("button" "<button type=\"${1:submit}\">$0</button>" "button" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/button" nil nil)
                       ("br" "<br />" "br" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/br" nil nil)
                       ("body" "<body>\n	$0\n</body>" "body" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/body" nil nil)
                       ("blockquote" "<blockquote>\n	$0\n</blockquote>" "blockquote" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/blockquote" nil nil)
                       ("bdo:r" "<bdo dir=\"rtl\">$0</bdo>" "bdo:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/bdo_r" nil nil)
                       ("bdo:l" "<bdo dir=\"ltr\">$0</bdo>" "bdo:l" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/bdo_l" nil nil)
                       ("bdo" "<bdo dir=\"$1\">$0</bdo>" "bdo" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/bdo" nil nil)
                       ("bdi" "<bdi>$0</bdo>" "bdi" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/bdi" nil nil)
                       ("base" "<base href=\"$1\" target=\"$0\" />" "base" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/base" nil nil)
                       ("backtab" "&#x21E4;" "backtab" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/backtab" nil nil)
                       ("backspace" "&#x232B;" "backspace" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/backspace" nil nil)
                       ("b" "<b>$0</b>" "b" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/b" nil nil)
                       ("audio" "<audio src=\"$1>$0</audio>" "audio" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/audio" nil nil)
                       ("attr+" "${1:attribute}=\"${2:property}\" attr+" "attr+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/attr+" nil nil)
                       ("attr" "${1:attribute}=\"${0:property}\"" "attr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/attr" nil nil)
                       ("aside." "<aside class=\"$1\">\n	$0\n</aside>" "aside." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/aside." nil nil)
                       ("aside#" "<aside id=\"$1\">\n	$0\n</aside>" "aside#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/aside#" nil nil)
                       ("aside" "<aside>\n	$0\n</aside>" "aside" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/aside" nil nil)
                       ("article." "<article class=\"$1\">\n	$0\n</article>" "article." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/article." nil nil)
                       ("article#" "<article id=\"$1\">\n	$0\n</article>" "article#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/article#" nil nil)
                       ("article" "<article>\n	$0\n</article>" "article" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/article" nil nil)
                       ("area:r" "<area shape=\"rect\" coords=\"$1\" href=\"$2\" alt=\"$0\" />" "area:r" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/area_r" nil nil)
                       ("area:p" "<area shape=\"poly\" coords=\"$1\" href=\"$2\" alt=\"$0\" />" "area:p" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/area_p" nil nil)
                       ("area:d" "<area shape=\"default\" coords=\"$1\" href=\"$2\" alt=\"$0\" />" "area:d" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/area_d" nil nil)
                       ("area:c" "<area shape=\"circle\" coords=\"$1\" href=\"$2\" alt=\"$0\" />" "area:c" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/area_c" nil nil)
                       ("area+" "<area shape=\"${1:rect}\" coords=\"$2\" href=\"$3\" alt=\"$4\" />\narea+" "area+" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/area+" nil nil)
                       ("area" "<area shape=\"${1:rect}\" coords=\"$2\" href=\"$3\" alt=\"$0\" />" "area" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/area" nil nil)
                       ("alt" "alt=\"$1\"" "alt" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/alt" nil nil)
                       ("address" "<address>\n	$0\n</address>" "address" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/address" nil nil)
                       ("ac" "<a href=\"\">${0:}</a>" "ac" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/ac" nil nil)
                       ("abbr" "<abbr title=\"$1\">$0</abbr>" "abbr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/abbr" nil nil)
                       ("a:mail" "<a href=\"mailto:${1:joe@example.com}?subject=${2:feedback}\">${0:email me}</a>" "a:mail" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/a_mail" nil nil)
                       ("a:ext" "<a href=\"http://${1:example.com}\">${0:$1}</a>" "a:ext" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/a_ext" nil nil)
                       ("a." "<a class=\"$1\" href=\"${2:#}\">${0:$1}</a>" "a." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/a." nil nil)
                       ("a#" "<a id=\"$1\" href=\"${2:#}\">${0:$1}</a>" "a#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/a#" nil nil)
                       ("a" "<a href=\"${1:#}\">${0:$1}</a>" "a" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/a" nil nil)
                       ("//" "<!-- $1 -->$0" "//" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/__" nil nil)
                       ("." "class=\"$1\"" "." nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/_" nil nil)
                       ("#" "id=\"$1\"" "#" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/html-mode/#" nil nil)))


;;; Do not edit! File generated at Sun Oct 25 17:07:30 2015
