;;; Compiled snippets and support files for `c++-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'c++-mode
                     '(("vector" "std::vector<${1:T}> $2;" "vector" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/vector" nil nil)
                       ("uset" "std::unordered_set<${1:T}> $2;" "uset" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/uset" nil nil)
                       ("umset" "std::unordered_multiset<${1:T}> $2;" "umset" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/umset" nil nil)
                       ("ummap" "std::unordered_multimap<${1:Key}, ${2:T}> $3;" "ummap" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/ummap" nil nil)
                       ("umap" "std::unordered_map<${1:Key}, ${2:T}> $3;" "umap" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/umap" nil nil)
                       ("try" "try {\n  \n}catch($1) {\n  \n}\n\n\n" "try" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/try" nil nil)
                       ("stack" "std::stack<${1:T}> $2;" "stack" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/stack" nil nil)
                       ("set" "std::set<${1:T}> $2;" "set" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/set" nil nil)
                       ("sca" "static_cast<${1:unsigned}>(${2:expr})$3" "sca" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/sca" nil nil)
                       ("rca" "reinterpret_cast<${1:unsigned}>(${2:expr})$3" "rca" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/rca" nil nil)
                       ("queue" "std::queue<${1:T}> $2;" "queue" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/queue" nil nil)
                       ("pub" "public" "pub" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/pub" nil nil)
                       ("pro" "protected" "pro" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/pro" nil nil)
                       ("pri" "private" "pri" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/pri" nil nil)
                       ("pqueue" "std::priority_queue<${1:T}> $2;" "pqueue" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/pqueue" nil nil)
                       ("ns" "namespace ${1:`(file-name-base)`} {\n  $0\n} /* namespace $1 */" "ns" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/ns" nil nil)
                       ("mu" "mutable" "mu" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/mu" nil nil)
                       ("mset" "std::multiset<${1:T}> $2;" "mset" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/mset" nil nil)
                       ("mmap" "std::multimap<${1:Key}, ${2:T}> $3;" "mmap" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/mmap" nil nil)
                       ("mfun" "${4:void} ${1:`(file-name-base)`}::${2:memberFunction}($3) {\n  $0\n}" "mfun" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/mfun" nil nil)
                       ("map" "std::map<${1:Key}, ${2:T}> $3;" "map" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/map" nil nil)
                       ("lld" "[$1]($2){\n  $3\n};" "lld" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/lld" nil nil)
                       ("list" "std::list<${1:T}> $2;" "list" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/list" nil nil)
                       ("ld" "[$1]($2){$3};" "ld" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/ld" nil nil)
                       ("itera" "for (auto ${1:i} = ${2:container}.begin(); $1 != $2.end(); ++$1) {\n  ${3:std::cout << *$1 << std::endl;}\n}" "itera" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/itera" nil nil)
                       ("iter" "for (${1:std::vector}<${2:type}>::${3:const_iterator} ${4:i} = ${5:container}.begin(); $4 != $5.end(); ++$4) {\n  $6\n}\n" "iter" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/iter" nil nil)
                       ("incc" "#include <${1:iostream}>" "incc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/incc" nil nil)
                       ("fr" "friend" "fr" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/fr" nil nil)
                       ("fori" "for (int ${2:i} = 0; $2 < ${1:count}; $2${3:++}) {\n  $4\n}\n" "fori" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/fori" nil nil)
                       ("fore" "for (${1:auto} ${2:i} : ${3:container}) {\n  $4\n}" "fore" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/fore" nil nil)
                       ("flist" "std::forward_list<${1:T}> $2;" "flist" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/flist" nil nil)
                       ("dmfun2" "/*! \\brief ${8:Brief function description here}\n *\n *  ${9:Detailed description}\n *\n * \\param $4 ${10:Parameter description}\n * \\param $6 ${11:Parameter description}\n * \\return ${12:Return parameter description}\n */\n${7:void} ${1:`(file-name-base)`}::${2:memberFunction}(${3:Type} ${4:Parameter},${5:Type} ${6:Parameter}) {\n  $0\n}" "dmfun2" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/dmfun2" nil nil)
                       ("dmfun1" "/*! \\brief ${6:Brief function description here}\n *\n *  ${7:Detailed description}\n *\n * \\param $4 ${8:Parameter description}\n * \\return ${9:Return parameter description}\n */\n${5:void} ${1:`(file-name-base)`}::${2:memberFunction}(${3:Type} ${4:Parameter}) {\n  $0\n}" "dmfun1" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/dmfun1" nil nil)
                       ("dmfun0" "/*! \\brief ${4:Brief function description here}\n *\n *  ${5:Detailed description}\n *\n * \\return ${6:Return parameter description}\n */\n${3:void} ${1:`(file-name-base)`}::${2:memberFunction}() {\n  $0\n}" "dmfun0" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/dmfun0" nil nil)
                       ("deque" "std::deque<${1:T}> $2;" "deque" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/deque" nil nil)
                       ("dca" "dynamic_cast<${1:unsigned}>(${2:expr})$3" "dca" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/dca" nil nil)
                       ("cout" "std::cout << $1 << std::endl;" "cout" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/cout" nil nil)
                       ("cl" "/*! \\class $1\n *  \\brief ${3:Brief class description}\n *\n *  ${4:Detailed description}\n */\nclass ${1:`(file-name-base)`}\n{\npublic:\n  $1($2);\n  virtual ~$1();\n\nprotected:\n  m_$5; /*!< ${6:Member description} */\n};" "cl" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/cl" nil nil)
                       ("cin" "std::cin >> $1;" "cin" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/cin" nil nil)
                       ("cca" "const_cast<${1:unsigned}>(${2:expr})$3" "cca" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/cca" nil nil)
                       ("binc" "#include <boost/${1:shared_ptr}.hpp>" "binc" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/binc" nil nil)
                       ("array" "std::array<${1:T}, ${2:N}> $3;" "array" nil nil nil "/home/bruno/code/yasnippet-vim-snippets/snippets/c++-mode/array" nil nil)))


;;; Do not edit! File generated at Mon May  8 02:40:50 2017
